import * as React from 'react';

export const DummyText = () => {
    return <div>{`
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec finibus erat at risus hendrerit pellentesque. Sed nec vehicula ligula. Quisque a vehicula orci, id dictum libero. Phasellus varius semper convallis. Nullam nec eleifend erat. Sed consectetur, est sed scelerisque placerat, mi erat volutpat risus, sit amet placerat mi neque et ligula. Vestibulum urna elit, vulputate vel blandit id, vestibulum vel erat. Sed mattis, mauris nec tincidunt viverra, enim nisi vehicula orci, sit amet pellentesque sapien justo eget mauris. Sed ex ligula, posuere quis ligula quis, dapibus feugiat nibh. Quisque neque tortor, sodales ut purus hendrerit, posuere sodales purus.

    Quisque vel lacus metus. Suspendisse convallis venenatis odio, eget dapibus augue imperdiet id. Fusce consequat et purus a pretium. Donec eget massa maximus ex gravida ultricies nec in diam. Mauris nec libero nec nisi bibendum faucibus eget quis diam. Quisque maximus dui tortor, vitae tincidunt augue porta a. Ut pretium ut lorem ut sollicitudin. Vestibulum scelerisque est ligula, eget suscipit mi luctus sit amet.

    Sed eros felis, accumsan eu odio semper, tempus condimentum libero. Curabitur placerat lacus vel bibendum laoreet. In quis lectus sit amet enim finibus dignissim vel in felis. Praesent quis placerat quam. Nam mattis et odio sit amet tincidunt. Integer ullamcorper cursus mauris et lacinia. In hac habitasse platea dictumst.

    Mauris bibendum erat nec libero cursus accumsan. Pellentesque eget ultricies lacus. Etiam nec turpis et sem iaculis bibendum. Phasellus laoreet viverra mollis. Quisque et magna ex. Etiam tempor, mauris in vehicula lacinia, mi nulla tincidunt leo, eget laoreet nisi diam sit amet lorem. In ac mollis lacus, at tempus libero. Donec bibendum in arcu ut commodo. Maecenas a suscipit arcu. Suspendisse rutrum ligula non nibh sagittis, vel elementum magna euismod. Pellentesque volutpat eu sapien quis aliquam. Duis porttitor dolor iaculis feugiat semper. Cras vel elit elementum, rutrum metus ac, maximus enim. Curabitur non finibus nisi. Donec rhoncus eget massa a feugiat. Cras nec ornare arcu.

    Suspendisse sit amet urna a leo egestas convallis vitae eget eros. Donec dapibus eros vitae auctor lacinia. Nullam quis enim sapien. Praesent a gravida augue. Donec ultrices, lorem eu sodales fermentum, eros nulla rutrum nisi, quis viverra risus mi non ex. Fusce et facilisis erat. Quisque lectus ante, hendrerit vel quam sit amet, dignissim aliquam diam. Quisque eu euismod nunc. Etiam non bibendum augue. Vestibulum purus libero, luctus a lorem ut, convallis pellentesque magna. Mauris consequat mollis est, eu sodales nulla scelerisque vitae. Integer sed est sagittis, tincidunt ex in, mollis justo. Nam viverra laoreet augue. Sed eleifend commodo purus, at aliquam diam luctus et. Maecenas euismod vulputate lobortis.

    Morbi id tellus quis massa sodales hendrerit ut eget turpis. Etiam vulputate ornare quam nec vestibulum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur facilisis venenatis eros, vitae vulputate nibh malesuada eu. Vestibulum eu nunc vitae arcu iaculis luctus eu non lectus. Donec ornare, ligula quis mattis rhoncus, sapien arcu pellentesque purus, id mollis ipsum orci nec arcu. Nulla nec magna tellus. Donec magna tellus, aliquam nec feugiat sit amet, fermentum ac ipsum. Cras vitae nisi a risus congue dictum id vitae elit. Donec et consectetur ex. Donec auctor semper laoreet. Maecenas sodales metus eget dolor molestie, sed tempor arcu pharetra. Curabitur sed felis eu justo pharetra imperdiet dictum quis magna. Sed scelerisque placerat mauris, sed blandit ante venenatis faucibus. Nunc sed ante at lacus molestie dignissim.
`}</div>
}